apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: observability

data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:

    processors:
      batch:

    exporters:
      prometheus:
        endpoint: "0.0.0.0:8889"

      loki:
        endpoint: http://loki-gateway.observability.svc.cluster.local/loki/api/v1/push

      otlp/tempo:
        endpoint: tempo-distributor.observability.svc.cluster.local:4317
        tls:
          insecure: true

      logging:
        loglevel: debug

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp/tempo]

        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [prometheus]

        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [loki]